### ISSUE TITLE
Şifre kullanmadan çalıştırma

### ISSUE THREAD

**Issue by mhmtkrktr** [8100d1r0n/bin#1]
Güzel çalışma , eline sağlık. 
Peki şifrelenmiş betiği, şifre kullanmadan çalıştırmak mümkün mü?
Yani, sadece görünürlüğü bu şekilde olsun ama çalıştırılacağı zaman şifre sormasın şeklinde.

**Comment by 8100d1r0n** [comment]
Tesekur ederim @mhmtkrktr.
Cesitli yontemler de uygulanabilir ama burada  ben basit bir yontemini soyleyebilirim.

``` sh
$ openssl enc -d -aes-256-cbc -a  -k FilePasswd -in test-enc.sh | sh -
```

Seklinde kullanilabilir.
Eger bir txt dosyasinda yazili ise sifre,

``` sh
-k `cat ~/passwd.txt`
```

``` sh
-pass file:passwd.txt
```

gibi duzenlemeler ile kullanilabilir.
Umarim yardimci olabilmisimdir.

**Comment by mhmtkrktr** [comment]
Teşekkür ederim @8100d1r0n
Aslında önemli olan, başka kullanıcılar şifreyi kullanarak betiği normal okunabilir haline dönüştürebiliyor mu?
Yukarda ki yöntemlerde şifre, diğer kullanıcılar tarafından bulunabilir. Yöntemini bilen için, herhangi bir engel kalmıyor bu durumda. Fakat okunabilir haline geri alınamıyorsa bu daha iyi olurdu. Şifreyi bilmekte işe yaramamış olur bu şekilde.

**Comment by 8100d1r0n** [comment]
Evet, diger kullacilar da sifreyi bildikten sonra, hem okuyabilir, hem calistirabilir. Okuyamazsak bizde calistiramayiz. Eger ben dogru anladiysam. Siz sadece kendiniz de calismasini, sifreyi bilseler de baska sistemler de okunmasini istemiyorsunuz. 
Sanirim bunun icin size soyle bir fikir verebilirim.
Cift anahtar sistemi. Sizin icin sifreleme yapabilirler ama sifre acici anahtar olmadan sifreyi bilseler de acamazlar. Gpg ilk aklima gelen. Openssl de kullanilabilir  diye dusunuyorum. Ben kullanmak istedim acikcasi ama size boyle bir yol gosterebilirim.

**Comment by mhmtkrktr** [comment]
*_Evet, diger kullacilar da sifreyi bildikten sonra, hem okuyabilir, hem calistirabilir. Okuyamazsak bizde calistiramayiz. Eger ben dogru anladiysam. Siz sadece kendiniz de calismasini, sifreyi bilseler de baska sistemler de okunmasini istemiyorsunuz. *_ 

Sormak istediğim, şifre olsun veya olmasın her sistemde çalışsın. Sadece o veya bu şekilde içeriği hiç kimse tarafından okunamasın.  
openssl 'in şifrelemeyi açıp, aynı dosyayı içeriği okunabilir duruma getirme gibi bir özelliği yoksa, bu söylediğim oluyor. Merak ettiğim bu özelliğin olup olmadığı.

**Comment by 8100d1r0n** [comment]
Bunun  icin betik derleyici bulunmakta. [(shc)](https://github.com/neurobin/shc)
Onun disinda obfuscation olaylarina bakilabilir. [(ShellCrypt)](https://sourceforge.net/projects/shellcrypt/)
Openssl icin konusuyorsak,  nasil bir yol izlenir acikcasi arastirmak lazim. Suan icin kesin bisey soyleyemiyorum.

**Comment by mhmtkrktr** [comment]
Sorumun cevabı shc imiş. Teşekkür ederim.

2016-08-24 19:13 GMT+03:00 8100d1r0n notifications@github.com:
